openapi: 3.0.0
info:
  title: mvc__
  version: 0.6.1
  description: mvc test
paths:
  /users/{id}:
    get:
      summary: GET1
      description: get one user by user id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: all right
          content:
            application/json:
              schema:
                type: string
                example:
                  id: 1
                  username: test

        "400":
          description: invalid user id or endpoint
  /users/range/{from}/{to}:
    get:
      summary: GET10
      description: get one user by user id
      parameters:
        - name: from
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: to
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: all right
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
        400:
          description: invalid user id or endpoint
components:
  schemas:
    user:
      type: object
      properties:
        id:
          type: integer
          format: int32
          example: 1
        username:
          type: string
          example: user
  